# Generated by Django 6.0 on 2026-02-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
    ]
